name: tests

on:
  push:
    branches:
      - master
      - "*.x"
  pull_request:
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: read

jobs:
  tests:
    runs-on: ubuntu-latest

    name: Node ${{ matrix.node }}

    strategy:
      fail-fast: false
      matrix:
        node: [22, 24]

    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Install pnpm
        uses: pnpm/action-setup@0977fd99725f1db4007ccb2928dbb4e90d06cc86 # v6.0.10

      - name: Set up Node
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v6
        with:
          node-version: ${{ matrix.node }}
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: ESLint
        run: pnpm run lint

      - name: Type check
        run: pnpm run typecheck

      - name: Execute tests
        run: pnpm test

      - name: Audit dependencies
        run: pnpm audit
