name: tests

on:
  push:
    branches:
      - master
      - "*.x"
  pull_request:
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: read

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Install pnpm
        uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9
        with:
          version: 11.1.1

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: ESLint
        run: pnpm run lint

      - name: Execute tests
        run: pnpm test

      - name: Audit dependencies
        run: pnpm audit
